### ISSUE TITLE
Add nodegit@0.28.0-alpha.21

### ISSUE THREAD

**Issue by abhishiv** [bitmeal/nodegit-alpine#2]
Hello, 

Thanks for the very useful images - specially due to ARM support,

Would it be possible to add the version '0.28.0-alpha.21' to the build matrix?

**Comment by bitmeal** [comment]
Images are building at the moment, took a little while to sort out some issues with the automated build process.

As even the alpha version is quite old, adding it to the list of build versions sounds reasonable.
